export const CartCheckoutStatus = {

    CHECKOUT_STARTED:"CHECKOUT_STARTED",
    CHECKOUT_NOT_STARTED:"CHECKOUT_NOT_STARTED",
    CHECKOUT_COMPLETED:"CHECKOUT_COMPLETED"

}

export const CartCheckoutAction = {

    START_CHECKOUT:"START_CHECKOUT",
    ABORT_CHECKOUT:"ABORT_CHECKOUT",
    COMPLETE_CHECKOUT:"COMPLETE_CHECKOUT"

}

export const CartContentsAction = {

    ADD_ITEM:"ADD_ITEM",
    CREATE_CART:"CREATE_CART"

}

export const ErrorCode = {

    CART_NOT_FOUND: "CART_NOT_FOUND",
    CART_TRANSACTION_ALREADY_STARTED: "CART_TRANSACTION_ALREADY_STARTED",
    CART_TRANSACTION_ALREADY_COMPLETED: "CART_TRANSACTION_ALREADY_COMPLETED",
    FIELD_VALIDATION_FAILURE: "FIELD_VALIDATION_FAILURE",
    PAYMENT_NOT_ACCEPTED: "PAYMENT_NOT_ACCEPTED"

}

export const VendorPaymentOutcome = {

    NOT_ACCEPTED: "NOT_ACCEPTED",
    ACCEPTED: "ACCEPTED"

}

export const TransactionAction = {

    CREATE_TRANSACTION: "CREATE_TRANSACTION",
    ABORT_TRANSACTION: "ABORT_TRANSACTION",
    COMPLETE_TRANSACTION: "COMPLETE_TRANSACTION"
}

export const TransactionType = {
    CART_CHECKOUT: "CART_CHECKOUT"
}